package com.clumsy.googletest;

public class GymList extends GoogleTest {

	public static final String[] ALL_STALBANS_GYMS = {
		"Abbey Theatre",
		"Apollo Court Fountain",
		"Apple Tree Project",
		"Art & Design Building",
		"Batchwood Turret",
		"Batford Sign and Jubilee Sculpture",
		"Batford Springs Damp Woodland Sign",
		"Bernard's Heath",
		"Birklands Park Sign",
		"Blackberry Arch",
		"Bleak House",
		"Bowers Parade Sensory Garden",
		"Bricket Wood Railway Station",
		"Bricket Wood United Reformed Church",
		"Brickett Wood Common 2",
		"Brickett Wood Common Circular Walk Marker",
		"Brooke End Play Area",
		"Butterflies and Flowers Metal Artwork",
		"Butterfly World Gates",
		"Carving London Colney",
		"Cell Barnes Orchard",
		"Centurion's Statue",
		"Chapel of Peace",
		"Chiswell Green Post Office",
		"Christ Church St Albans",
		"City of St. Alban Marker",
		"Clarence Park Bandstand",
		"Cock O' the North",
		"Colney Heath Community Park",
		"Colney Heath F C and Social Club",
		"Colney Heath Village Hall",
		"Comet Racer G-ACSS",
		"Couple Sculpture",
		"Cumberland Gardens",
		"Cunningham Hill Football Park North Entrance",
		"Cunningham Hub",
		"Devil's Dyke",
		"Diamond Jubilee Torch",
		"Discover an amazing magic carpet",
		"Ellenbrook Fields Story Zone",
		"Entrance to Roman Theatre of Verulamium",
		"Entrance to Rothamsted Park",
		"Fleetville Post Office",
		"Flower Lady",
		"Football Park Redbourn",
		"Forest Town Church",
		"Fountain in Clarence Park",
		"Gardens Of The Rose",
		"George Marten's Cross",
		"Gobions Wood Nature Reserve",
		"God is with us",
		"Gorhambury",
		"Greenwood Park and Nature Trail",
		"Greenwood Park Community Centre",
		"Harpenden's Ups And Downs",
		"Harpenden Hilda Lydekker War Memorial Stone",
		"Harpenden Indoor Bowls Club",
		"Harpenden Lydekker Park",
		"Harpenden Railway Station",
		"Hatfield Aerodrome Heritage Trail",
		"Hertfordshire Fisheries",
		"Highfield Park - Tyttenhanger",
		"Highfield Park Wooden Sculpture",
		"Hill End Commemorative Garden",
		"Hill End Garden of Rest",
		"Hilldyke Road Play Area",
		"Homewood Road United Reform Church",
		"Honey Bunny",
		"How Wood Nature Trail",
		"How Wood Railway Station",
		"In Fond Memory Of Leonard Laidlaw",
		"Jersey Farm Play Area",
		"Jersey Farm Woodland Park",
		"Jesus Cross at St Saviours",
		"John Bunyan's Chimney",
		"Landmark Centre",
		"Leoro Gallery",
		"Library - London Colney",
		"London Road Club",
		"Marshalswick Library, St Albans",
		"Marshalswick Post Office",
		"Martin's Post Office",
		"Melissa Field 1933",
		"Milestone at de Havilland Campus",
		"Morton House",
		"N&C Entrance",
		"Newgate Close Play Area I",
		"Nick Marshall Plaque",
		"Nomansland Common",
		"Nomansland Model Aircraft Landing Strip",
		"Oaklands College Clock",
		"Our Lady of Walsingham Catholic Church",
		"Park Street Mainline Station",
		"Pink Chicken",
		"Pitch 4",
		"Plough and Harrow",
		"Redbourne Library",
		"Redbourne Watermill",
		"Religious Society of Friends (Quakers)",
		"River Ver Fishing Bench",
		"River Ver Trail Marker 1",
		"Roman City Defence Wall",
		"Roman Mosaic",
		"Roman Theatre of Verulamium",
		"Romeland House",
		"Rothampstead Skatepark",
		"Rothampsted Park Wildflower Meadows",
		"Rothamstead Millstone",
		"Saint Peter's Anglican Church",
		"Saint Stephens Church",
		"Salmon Run",
		"Sandridge Centenary of Parish Councils Plaque",
		"Selectaglaze Crest, Dieu Et Mon Droit",
		"Six Bells Public House",
		"Sopwell Gate Lodge",
		"Sopwell Green Space",
		"Sopwell House",
		"Sopwell Nunnery",
		"Sopwell Nunnery Green Space",
		"Space-Time Portal",
		"SS Alban and Stephen Catholic Church",
		"St Albans AOG Church",
		"St Albans Cycles",
		"St Albans North Town Marker",
		"St Albans Royal Mail Sorting Office",
		"St Albans South Town Marker",
		"St Albans Town Hall",
		"St Albans West Town Marker",
		"St Julian Church",
		"St Leonards Church",
		"St Luke's Church Brickett Wood",
		"St Luke's Church Cell Barnes",
		"St Mary's Church, Redbourne",
		"St Mary the Virgin",
		"St Michael's Manor",
		"St Paul's Church",
		"St Saviour's Church",
		"St Thomas More Roman Catholic Church",
		"St. Albans Rugby Club",
		"St.Albans Civic Society Award 1988",
		"St.Stephens Hill Pond",
		"The Ancient Briton",
		"The Boot Inn",
		"The Castle Inn",
		"The Cathedral & Abbey Church of Saint Alban",
		"The Cock",
		"The Cricketers of Redbourn Public House",
		"The Golden Lion",
		"The Holly Bush",
		"The Hope & Anchor",
		"The London Gate and Roman Wall",
		"The Mermaid",
		"The Midland Railway Arch",
		"The National Willow Collection",
		"The Old Clock Tower at Napsbury Park",
		"The Old Hat Factory St. Albans",
		"The Plough",
		"The Rat's Castle",
		"The Rose and Crown",
		"Three Kings",
		"Toulmin Drive Fort",
		"Tree Art",
		"Tyttenhanger Green Sign",
		"Upper Lea Valley Group Meeting Point",
		"Ver Valley Walk 5",
		"Verdi's",
		"Verulam Consultants",
		"Verulamium Park Entrance Map",
		"Verulamium Park South Entrance",
		"Victoria's Cannon",
		"Victoria Pub",
		"War Memorial",
		"Water Tower Shakespeare Road",
		"Watercress Nature Reserve",
		"Welcome To The Magical Wood Wooden Marker",
		"Wheathampstead Cricket Club",
		"Wheathampstead Methodist Chapel",
		"Wheathampstead Sign",
		"Wildlife Totem",
		"Willows Farm Falconry Sculpture",
		"Woodland Cycle Path",
		"Ye Olde Fighting Cocks"
	};
}
